import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { isModerationActive } from "@/lib/utils";
import type { ModerationAction, Profile, UserRole } from "@/lib/types";
export async function getAuthContext(){const s=await createClient();const{data:u,error}=await s.auth.getUser();if(error||!u.user)return null;const[{data:profile},{data:mods},aal,legal]=await Promise.all([s.from("profiles").select("id,username,display_name,bio,role,suspended,terms_version,privacy_version,guidelines_version,legal_accepted_at,mfa_required,created_at,updated_at").eq("id",u.user.id).single(),s.from("moderation_actions").select("id,user_id,kind,reason,created_by,created_at,expires_at,revoked_at,revoked_by,revoke_reason").eq("user_id",u.user.id).is("revoked_at",null).order("created_at",{ascending:false}),s.auth.mfa.getAuthenticatorAssuranceLevel(),s.rpc("has_current_legal_acceptance",{uid:u.user.id})]);if(!profile)return null;const active=((mods||[])as ModerationAction[]).filter(isModerationActive);const muted=active.some(x=>x.kind==="mute");const blockedAction=active.find(x=>x.kind==="ban"||x.kind==="suspend");const actualRole=profile.role as UserRole;const store=await cookies();const userView=actualRole==="sysadmin"&&store.get("zionxyos_view")?.value==="user";const effectiveRole:UserRole=userView?"user":actualRole;const hasAal2=aal.data?.currentLevel==="aal2";const isStaff=actualRole==="admin"||actualRole==="sysadmin";const legalAccepted=Boolean(legal.data)&&!legal.error;const blocked=Boolean(profile.suspended||blockedAction);return{user:u.user,profile:profile as Profile,actualRole,effectiveRole,userView,activeModeration:active,muted,blocked,blockedAction,hasAal2,isStaff,legalAccepted,canContribute:!muted&&!blocked&&legalAccepted};}
export async function requireUser(options:{requireLegal?:boolean}={requireLegal:true}){const c=await getAuthContext();if(!c)redirect("/login");if(c.blocked)redirect("/suspended");if(options.requireLegal!==false&&!c.legalAccepted)redirect("/legal/accept");return c;}
export async function requireContributor(){const c=await requireUser();if(!c.canContribute)redirect("/dashboard?error=Your account cannot contribute right now.");return c;}
export async function requireAdmin(options:{requireMfa?:boolean}={requireMfa:true}){const c=await requireUser();if(c.userView||!(c.actualRole==="admin"||c.actualRole==="sysadmin"))redirect("/dashboard");if(options.requireMfa!==false&&!c.hasAal2)redirect("/mfa");return c;}
export async function requireSysadmin(options:{requireMfa?:boolean}={requireMfa:true}){const c=await requireUser();if(c.userView||c.actualRole!=="sysadmin")redirect("/dashboard");if(options.requireMfa!==false&&!c.hasAal2)redirect("/mfa");return c;}
