"use server";
import { revalidatePath } from "next/cache";import { redirect } from "next/navigation";import { requireSysadmin } from "@/lib/auth";import { createClient } from "@/lib/supabase/server";import { APP_VERSION } from "@/lib/version";
function text(f:FormData,k:string,n=2000){return String(f.get(k)||"").trim().slice(0,n);}
function tuple(v:string){const m=v.match(/^(\d+)\.(\d+)(?:\.(\d+))?/);return m?[+m[1],+m[2],+(m[3]||0)]:null;}
function newer(a:string,b:string){const x=tuple(a),y=tuple(b);if(!x||!y)return false;for(let i=0;i<3;i++){if(x[i]>y[i])return true;if(x[i]<y[i])return false;}return false;}
function trustedManifestUrl(raw:string){const u=new URL(raw);if(u.protocol!=="https:")throw new Error("Release manifest must use HTTPS.");if(u.username||u.password)throw new Error("Release manifest URL must not contain credentials.");if(u.port&&u.port!=="443")throw new Error("Release manifest must use the standard HTTPS port.");const h=u.hostname.toLowerCase().replace(/^\[|\]$/g,"");const allowed=(process.env.ZIONXYOS_RELEASE_MANIFEST_ALLOWED_HOSTS||"").split(",").map(x=>x.trim().toLowerCase()).filter(Boolean);if(process.env.NODE_ENV==="production"&&!allowed.length)throw new Error("ZIONXYOS_RELEASE_MANIFEST_ALLOWED_HOSTS must be configured before production manifest checks.");if(allowed.length&&!allowed.includes(h))throw new Error("Release manifest host is not in the server allowlist.");const ipv4=h.match(/^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})$/);if(h==="localhost"||h.endsWith(".localhost")||h.endsWith(".local")||h==="::1"||h.startsWith("fc")||h.startsWith("fd")||h.startsWith("fe80")||h.startsWith("::ffff:127.")||h.startsWith("::ffff:10.")||h.startsWith("::ffff:192.168.")||h.startsWith("::ffff:169.254.")||h.startsWith("::ffff:100.")||(/^::ffff:172\.(1[6-9]|2\d|3[01])\./.test(h))||(ipv4&&(()=>{const a=Number(ipv4[1]),b=Number(ipv4[2]),c=Number(ipv4[3]),d=Number(ipv4[4]);if([a,b,c,d].some(n=>n<0||n>255))return true;return a===10||a===127||a===0||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&b===168)||(a===100&&b>=64&&b<=127);})()))throw new Error("Release manifest must use a public HTTPS host.");return u;}
function validFutureDate(raw:string,label:string){if(!raw)return null;const d=new Date(raw);if(!Number.isFinite(d.getTime())||d.getTime()<=Date.now())throw new Error(`${label} must be a valid future date and time.`);return d.toISOString();}
export async function saveSystemSettingsAction(f:FormData){await requireSysadmin();const s=await createClient();const values:[string,unknown][]=[["site_name",text(f,"site_name",100)||"Zionxyos"],["tagline",text(f,"tagline",200)],["logo_url",text(f,"logo_url")],["favicon_url",text(f,"favicon_url")],["legal_contact_email",text(f,"legal_contact_email",320)],["registration_enabled",f.get("registration_enabled")==="on"],["article_creation_enabled",f.get("article_creation_enabled")==="on"],["discussion_enabled",f.get("discussion_enabled")==="on"],["media_uploads_enabled",f.get("media_uploads_enabled")==="on"],["image_uploads_enabled",f.get("image_uploads_enabled")==="on"],["video_uploads_enabled",f.get("video_uploads_enabled")==="on"],["maintenance_mode",f.get("maintenance_mode")==="on"],["max_image_bytes",Math.max(1048576,Math.min(52428800,Math.round(Number(f.get("max_image_mib"))||10)*1048576))],["max_video_bytes",Math.max(1048576,Math.min(52428800,Math.round(Number(f.get("max_video_mib"))||50)*1048576))],["release_channel",["stable","beta","development"].includes(text(f,"release_channel",30))?text(f,"release_channel",30):"stable"],["release_manifest_url",text(f,"release_manifest_url")]];const{error}=await s.rpc("sysadmin_set_settings",{settings_payload:Object.fromEntries(values)});if(error)redirect(`/admin/settings?error=${encodeURIComponent(error.message)}`);revalidatePath("/");revalidatePath("/admin/settings");redirect("/admin/settings?success=System%20settings%20saved.");}
export async function createAnnouncementAction(f:FormData){const c=await requireSysadmin();const title=text(f,"title",160),body=text(f,"body",2000),kind=text(f,"kind",30),audience=text(f,"audience",30),end=text(f,"ends_at",80);if(!title||!body||!["info","warning","maintenance"].includes(kind)||!["all","authenticated","staff"].includes(audience))redirect("/admin/settings?error=Invalid%20announcement.");let endsAt:string|null=null;try{endsAt=validFutureDate(end,"Announcement expiry");}catch(e){redirect(`/admin/settings?error=${encodeURIComponent(e instanceof Error?e.message:"Invalid announcement expiry.")}`);}const s=await createClient();const{error}=await s.from("site_announcements").insert({title,body,kind,audience,ends_at:endsAt,active:true,created_by:c.user.id});if(error)redirect(`/admin/settings?error=${encodeURIComponent(error.message)}`);revalidatePath("/");redirect("/admin/settings?success=Announcement%20published.");}
export async function deleteAnnouncementAction(f:FormData){await requireSysadmin();const s=await createClient();const{error}=await s.from("site_announcements").delete().eq("id",text(f,"id",64));if(error)redirect(`/admin/settings?error=${encodeURIComponent(error.message)}`);revalidatePath("/");redirect("/admin/settings?success=Announcement%20deleted.");}
export async function checkUpdateAction(){await requireSysadmin();const s=await createClient();const{data:r}=await s.from("site_settings").select("value").eq("key","release_manifest_url").maybeSingle();const manifest=typeof r?.value==="string"?r.value:"";let status="informational",details:Record<string,unknown>={current_version:APP_VERSION};if(manifest){try{const u=trustedManifestUrl(manifest);const res=await fetch(u,{cache:"no-store",redirect:"error",signal:AbortSignal.timeout(12000),headers:process.env.ZIONXYOS_UPDATE_WEBHOOK_TOKEN?{Authorization:`Bearer ${process.env.ZIONXYOS_UPDATE_WEBHOOK_TOKEN}`}:{}});if(!res.ok)throw new Error(`Manifest returned HTTP ${res.status}.`);const declared=Number(res.headers.get("content-length")||0);if(declared>1048576)throw new Error("Release manifest is too large.");const payload=await res.text();if(payload.length>1048576)throw new Error("Release manifest is too large.");const raw:unknown=JSON.parse(payload);const obj=raw&&typeof raw==="object"&&!Array.isArray(raw)?raw as Record<string,unknown>:{};const latest=typeof obj.version==="string"?obj.version.slice(0,40):null;details={current_version:APP_VERSION,latest_version:latest,update_available:latest?newer(latest,APP_VERSION):false,notes:typeof obj.notes==="string"?obj.notes.slice(0,4000):null,url:typeof obj.url==="string"?obj.url.slice(0,2000):null};status="success";}catch(e){status="failed";details={...details,message:e instanceof Error?e.message:"Update check failed."};}}else details={...details,message:"No trusted release manifest URL is configured."};const{error:historyError}=await s.rpc("sysadmin_record_update_history",{action_name:"check",from_version_value:APP_VERSION,target_version_value:typeof details.latest_version==="string"?details.latest_version:"",status_name:status,details_payload:details});if(historyError)redirect(`/admin/system?error=${encodeURIComponent(`Update check finished, but its audit record could not be saved: ${historyError.message}`)}`);revalidatePath("/admin/system");redirect(`/admin/system?${status==="failed"?"error":"success"}=${encodeURIComponent(status==="success"?"Update check completed.":String(details.message||"Update check recorded."))}`);}
export async function triggerDeployAction(f:FormData){await requireSysadmin();const hook=process.env.VERCEL_DEPLOY_HOOK_URL;if(!hook)redirect("/admin/system?error=VERCEL_DEPLOY_HOOK_URL%20is%20not%20configured.");const target=text(f,"target_version",40);const confirmation=text(f,"deploy_confirmation",20);if(!target)redirect("/admin/system?error=Enter%20the%20target%20version%20before%20deploying.");if(confirmation!=="DEPLOY")redirect("/admin/system?error=Type%20DEPLOY%20to%20confirm%20the%20production%20deployment.");if(!newer(target,APP_VERSION))redirect(`/admin/system?error=${encodeURIComponent(`Target version must be newer than ${APP_VERSION}.`)}`);const hookUrl=(()=>{try{const parsed=new URL(hook);if(parsed.protocol!=="https:"||parsed.hostname!=="api.vercel.com"||parsed.username||parsed.password||(parsed.port&&parsed.port!=="443")||!parsed.pathname.startsWith("/v1/integrations/deploy/"))throw new Error("VERCEL_DEPLOY_HOOK_URL is not a valid credential-free Vercel Deploy Hook HTTPS URL.");return parsed;}catch(e){redirect(`/admin/system?error=${encodeURIComponent(e instanceof Error?e.message:"Invalid Vercel Deploy Hook URL.")}`);}})();const s=await createClient();let status="failed",message="";try{const r=await fetch(hookUrl,{method:"POST",cache:"no-store",redirect:"error",signal:AbortSignal.timeout(12000)});status=r.ok?"success":"failed";message=`Vercel deploy hook returned HTTP ${r.status}.`;}catch(e){message=e instanceof Error?e.message:"Deploy hook failed.";}const{error:historyError}=await s.rpc("sysadmin_record_update_history",{action_name:"deploy_hook",from_version_value:APP_VERSION,target_version_value:target,status_name:status,details_payload:{message}});if(historyError)redirect(`/admin/system?error=${encodeURIComponent(`${message} Update-history recording also failed: ${historyError.message}`)}`);revalidatePath("/admin/system");redirect(`/admin/system?${status==="success"?"success":"error"}=${encodeURIComponent(message)}`);}

export async function saveNoticeTemplateAction(formData: FormData) {
  const context = await requireSysadmin();
  const id = text(formData, "id", 64);
  const name = text(formData, "name", 100);
  const body = text(formData, "body", 1000);
  const kind = text(formData, "kind", 30);
  const active = formData.get("active") === "on";
  if (!name || !body || !["info", "warning", "maintenance", "quality"].includes(kind)) {
    redirect(`/admin/notices?error=${encodeURIComponent("Enter a valid notice name, body, and kind.")}`);
  }
  const supabase = await createClient();
  const payload = { name, body, kind, active };
  const result = id
    ? await supabase.from("notice_templates").update(payload).eq("id", id)
    : await supabase.from("notice_templates").insert({ ...payload, created_by: context.user.id });
  if (result.error) redirect(`/admin/notices?error=${encodeURIComponent(result.error.message)}`);
  revalidatePath("/admin/notices");
  revalidatePath("/admin/articles");
  redirect(`/admin/notices?success=${encodeURIComponent(id ? "Notice template updated." : "Notice template created.")}`);
}

export async function deleteNoticeTemplateAction(formData: FormData) {
  await requireSysadmin();
  const id = text(formData, "id", 64);
  const supabase = await createClient();
  const { count } = await supabase.from("article_notices").select("article_id", { count: "exact", head: true }).eq("notice_id", id);
  if ((count || 0) > 0) redirect(`/admin/notices?error=${encodeURIComponent("This template is assigned to one or more articles. Remove those assignments or deactivate the template instead.")}`);
  const { error } = await supabase.from("notice_templates").delete().eq("id", id);
  if (error) redirect(`/admin/notices?error=${encodeURIComponent(error.message)}`);
  revalidatePath("/admin/notices");
  redirect(`/admin/notices?success=${encodeURIComponent("Unused notice template deleted.")}`);
}
