import { Flash } from "@/components/Flash";
import { requireSysadmin } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { getAllSiteSettings } from "@/lib/settings";
import { createAnnouncementAction,deleteAnnouncementAction,saveSystemSettingsAction } from "@/actions/system";
import { formatBytes,formatDate } from "@/lib/utils";
export const metadata={title:"System settings · Administration"};
export default async function SettingsPage({searchParams}:{searchParams:Promise<{error?:string;success?:string}>}){await requireSysadmin();const m=await searchParams;const settings=await getAllSiteSettings();const s=await createClient();const{data:announcements}=await s.from("site_announcements").select("*").order("created_at",{ascending:false}).limit(50);return <><header className="classic-page-heading"><h1>System settings</h1><p>Site identity, feature switches, upload limits, maintenance, and release configuration.</p></header><Flash error={m.error} success={m.success}/><form action={saveSystemSettingsAction} className="settings-form">
<section className="admin-section"><h2>Wiki identity</h2><div className="form-grid two"><label><span>Site name</span><input name="site_name" required defaultValue={settings.siteName}/></label><label><span>Tagline</span><input name="tagline" defaultValue={settings.tagline}/></label><label><span>Logo URL</span><input type="url" name="logo_url" defaultValue={settings.logoUrl}/></label><label><span>Favicon URL</span><input type="url" name="favicon_url" defaultValue={settings.faviconUrl}/></label><label><span>Legal contact email</span><input type="email" name="legal_contact_email" defaultValue={settings.legalContactEmail}/></label></div></section>
<section className="admin-section"><h2>Feature switches</h2><div className="settings-check-grid"><label><input type="checkbox" name="registration_enabled" defaultChecked={settings.registrationEnabled}/> Allow account registration</label><label><input type="checkbox" name="article_creation_enabled" defaultChecked={settings.articleCreationEnabled}/> Allow article writing and submissions</label><label><input type="checkbox" name="discussion_enabled" defaultChecked={settings.discussionEnabled}/> Allow article discussions</label><label><input type="checkbox" name="media_uploads_enabled" defaultChecked={settings.mediaUploadsEnabled}/> Master media upload switch</label><label><input type="checkbox" name="image_uploads_enabled" defaultChecked={settings.imageUploadsEnabled}/> Allow image uploads</label><label><input type="checkbox" name="video_uploads_enabled" defaultChecked={settings.videoUploadsEnabled}/> Allow video uploads</label><label className="maintenance-switch"><input type="checkbox" name="maintenance_mode" defaultChecked={settings.maintenanceMode}/> <strong>Maintenance mode</strong> — close public pages to non-staff visitors</label></div></section>
<section className="admin-section"><h2>Media limits</h2><div className="form-grid two"><label><span>Maximum image size (MiB)</span><input type="number" name="max_image_mib" min={1} max={50} defaultValue={Math.round(settings.maxImageBytes/1048576)}/><small>Current: {formatBytes(settings.maxImageBytes)}</small></label><label><span>Maximum video size (MiB)</span><input type="number" name="max_video_mib" min={1} max={50} defaultValue={Math.round(settings.maxVideoBytes/1048576)}/><small>Storage hard cap: 50 MiB.</small></label></div></section>
<section className="admin-section"><h2>Release configuration</h2><div className="form-grid two"><label><span>Release channel</span><select name="release_channel" defaultValue={settings.releaseChannel}><option value="stable">Stable</option><option value="beta">Beta</option><option value="development">Development</option></select></label><label><span>Trusted release manifest URL</span><input type="url" name="release_manifest_url" defaultValue={settings.releaseManifestUrl} placeholder="https://example.com/zionxyos/manifest.json"/></label></div></section><button className="button primary" type="submit">Save system settings</button></form>
<section className="admin-section"><h2>Site announcements</h2><details className="admin-create-box"><summary>+ Publish announcement</summary><form action={createAnnouncementAction} className="wiki-fieldset"><div className="form-grid three"><label><span>Title</span><input name="title" required/></label><label><span>Kind</span><select name="kind"><option value="info">Info</option><option value="warning">Warning</option><option value="maintenance">Maintenance</option></select></label><label><span>Audience</span><select name="audience"><option value="all">Everyone</option><option value="authenticated">Signed-in users</option><option value="staff">Staff only</option></select></label></div><label><span>Message</span><textarea name="body" rows={4} required/></label><label><span>End date/time (optional)</span><input type="datetime-local" name="ends_at"/></label><button className="button" type="submit">Publish announcement</button></form></details>{!announcements?.length?<div className="wiki-message">No announcements have been created.</div>:<table className="management-table"><thead><tr><th>Announcement</th><th>Audience</th><th>Created</th><th></th></tr></thead><tbody>{announcements.map(x=><tr key={x.id}><td><strong>{x.title}</strong><div>{x.body}</div><div className="tiny-text">{x.kind} · {x.active?"active":"inactive"}</div></td><td>{x.audience}</td><td>{formatDate(x.created_at)}</td><td><form action={deleteAnnouncementAction}><input type="hidden" name="id" value={x.id}/><button className="button small danger" type="submit">Delete</button></form></td></tr>)}</tbody></table>}</section></>}
