import type { Metadata } from "next";
import Link from "next/link";
import "@/app/globals.css";
import { Header } from "@/components/Header";
import { getAuthContext } from "@/lib/auth";
import { getPublicSiteSettings } from "@/lib/settings";
import { getCanonicalSiteUrl } from "@/lib/site-url";
import { createClient } from "@/lib/supabase/server";
export async function generateMetadata():Promise<Metadata>{const s=await getPublicSiteSettings();const site=getCanonicalSiteUrl();return{metadataBase:new URL(site),title:{default:s.siteName,template:`%s — ${s.siteName}`},description:s.tagline,icons:s.faviconUrl?{icon:s.faviconUrl}:undefined,openGraph:{type:"website",siteName:s.siteName,title:s.siteName,description:s.tagline}}}
export default async function RootLayout({children}:{children:React.ReactNode}){const[settings,context]=await Promise.all([getPublicSiteSettings(),getAuthContext()]);const supabase=await createClient();const now=new Date().toISOString();const nowMs=Date.parse(now);const{data:raw}=await supabase.from("site_announcements").select("id,title,body,kind,audience,starts_at,ends_at,active").eq("active",true).lte("starts_at",now).order("starts_at",{ascending:false}).limit(5);const announcements=(raw||[]).filter(x=>(!x.ends_at||new Date(x.ends_at).getTime()>nowMs)&&(x.audience==="all"||(x.audience==="authenticated"&&Boolean(context))||(x.audience==="staff"&&Boolean(context?.isStaff&&!context.userView))));return <html lang="en"><body><Header/>{announcements.length>0&&<div className="site-width announcement-stack">{announcements.map(x=><div className={`site-announcement ${x.kind}`} key={x.id}><strong>{x.title}</strong><span>{x.body}</span></div>)}</div>}<main className="site-main">{children}</main><footer className="site-footer"><div className="site-width"><div>{settings.siteName} — {settings.tagline}.</div><div className="footer-links"><Link href="/about">About</Link> · <Link href="/special">Special pages</Link> · <Link href="/recent-changes">Recent changes</Link> · <Link href="/legal/terms">Terms</Link> · <Link href="/legal/privacy">Privacy</Link> · <Link href="/legal/guidelines">Guidelines</Link></div></div></footer></body></html>}
