"use client";
import { useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { formatBytes } from "@/lib/utils";
import type { MediaAsset } from "@/lib/types";
const ACCEPT={image:["image/jpeg","image/png","image/webp","image/gif"],video:["video/mp4","video/webm","video/ogg"]};
const EXTENSION:Record<string,string>={"image/jpeg":"jpg","image/png":"png","image/webp":"webp","image/gif":"gif","video/mp4":"mp4","video/webm":"webm","video/ogg":"ogg"};
function magic(mime:string,b:Uint8Array){const ascii=(a:number,z:number)=>String.fromCharCode(...b.slice(a,z));if(mime==="image/jpeg")return b[0]===255&&b[1]===216&&b[2]===255;if(mime==="image/png")return b.slice(0,8).join(",")==="137,80,78,71,13,10,26,10";if(mime==="image/gif")return ascii(0,4)==="GIF8";if(mime==="image/webp")return ascii(0,4)==="RIFF"&&ascii(8,12)==="WEBP";if(mime==="video/mp4")return ascii(4,8)==="ftyp";if(mime==="video/webm")return b.slice(0,4).join(",")==="26,69,223,163";if(mime==="video/ogg")return ascii(0,4)==="OggS";return false;}
export function DirectMediaUpload({kind,maxBytes,enabled,onAsset,onBusyChange}:{kind:"image"|"video";maxBytes:number;enabled:boolean;onAsset:(asset:MediaAsset)=>void;onBusyChange?:(busy:boolean)=>void}){const[file,setFile]=useState<File|null>(null);const[alt,setAlt]=useState("");const[busy,setBusy]=useState(false);const[msg,setMsg]=useState("");async function upload(){if(!file||busy)return;setMsg("");if(!enabled)return setMsg(`${kind} uploads are disabled.`);if(!ACCEPT[kind].includes(file.type))return setMsg("Unsupported file type.");if(file.size<1||file.size>maxBytes)return setMsg(`File must be smaller than ${formatBytes(maxBytes)}.`);const sig=new Uint8Array(await file.slice(0,32).arrayBuffer());if(!magic(file.type,sig))return setMsg("The file signature does not match the declared format.");setBusy(true);onBusyChange?.(true);const s=createClient();let objectPath="";try{const{data:u,error:ue}=await s.auth.getUser();if(ue||!u.user)throw new Error("Your session expired.");const ext=EXTENSION[file.type];if(!ext)throw new Error("Unsupported file type.");objectPath=`${u.user.id}/${crypto.randomUUID()}.${ext}`;const{error:up}=await s.storage.from("zionxyos-media").upload(objectPath,file,{contentType:file.type,upsert:false,cacheControl:"3600"});if(up)throw up;const publicUrl=s.storage.from("zionxyos-media").getPublicUrl(objectPath).data.publicUrl;const{data:asset,error:ie}=await s.from("media_assets").insert({owner_id:u.user.id,bucket:"zionxyos-media",object_path:objectPath,public_url:publicUrl,original_name:file.name.slice(0,255),media_kind:kind,mime_type:file.type,size_bytes:file.size,alt_text:kind==="image"?alt.trim().slice(0,500)||null:null}).select("*").single();if(ie||!asset){await s.storage.from("zionxyos-media").remove([objectPath]);throw ie||new Error("Could not create media record.");}onAsset(asset as MediaAsset);setFile(null);setMsg("Upload complete.");}catch(e){setMsg(e instanceof Error?e.message:"Upload failed.");}finally{setBusy(false);onBusyChange?.(false);}}
return <div className="direct-media-upload"><label><span>Upload {kind} from this computer</span><input type="file" accept={ACCEPT[kind].join(",")} disabled={!enabled||busy} onChange={e=>{setFile(e.target.files?.[0]||null);setMsg("");}}/></label>{kind==="image"&&<label><span>Alt text</span><input value={alt} onChange={e=>setAlt(e.target.value.slice(0,500))} placeholder="Describe the image for accessibility"/></label>}<div className="direct-media-actions"><button className="button" type="button" onClick={upload} disabled={!file||busy}>{busy?"Uploading…":"Upload"}</button>{file&&<small>{file.name} · {formatBytes(file.size)}</small>}</div>{msg&&<div className="tiny-text" role="status">{msg}</div>}</div>}
