import Link from "next/link";
import { requireUser } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { Flash } from "@/components/Flash";
import { StatusBadge } from "@/components/StatusBadge";
import { formatDate } from "@/lib/utils";
import { getPublicSiteSettings } from "@/lib/settings";
import type { RevisionStatus } from "@/lib/types";
export const metadata={title:"My contributions"};
type OwnRevision={id:string;article_id:string;title:string;status:RevisionStatus;updated_at:string;review_note:string|null;author_id:string};
type OwnArticle={id:string;title:string;slug:string;status:string;updated_at:string;published_at:string|null;author_id:string};
export default async function ContributionsPage({searchParams}:{searchParams:Promise<{error?:string;success?:string}>}){const c=await requireUser();const p=await searchParams;const s=await createClient();const settings=await getPublicSiteSettings();const{data:revisions}=await s.from("article_revisions").select("id,article_id,title,status,updated_at,review_note,author_id").eq("author_id",c.user.id).order("updated_at",{ascending:false});const ownRevisions=(revisions||[])as OwnRevision[];const ids=[...new Set(ownRevisions.map(x=>x.article_id))];const{data:articles}=ids.length?await s.from("articles").select("id,title,slug,status,updated_at,published_at,author_id").in("id",ids):{data:[]};const pageMap=new Map<string,OwnArticle>(((articles||[]) as OwnArticle[]).map(x=>[x.id,x]));const latest=new Map<string,OwnRevision>();for(const r of ownRevisions)if(!latest.has(r.article_id))latest.set(r.article_id,r);return <><header className="classic-page-heading action-heading"><div><h1>My contributions</h1><p>Drafts, submitted revisions, approved edits, and published pages you have contributed to.</p></div>{c.canContribute&&settings.articleCreationEnabled&&<Link href="/dashboard/articles/new" className="button primary">Create article</Link>}</header><Flash error={p.error} success={p.success}/>{!ids.length?<div className="wiki-message">You have not created or edited any article yet.</div>:<table className="management-table"><thead><tr><th>Page</th><th>Latest contribution</th><th>Last activity</th><th>Public page</th><th>Actions</th></tr></thead><tbody>{ids.map(id=>{const revision=latest.get(id)!;const article=pageMap.get(id);return <tr key={id}><td><strong>{revision.title||article?.title||"Untitled"}</strong>{revision.review_note&&revision.status==="changes_requested"&&<div className="tiny-text warning-text">Reviewer: {revision.review_note}</div>}</td><td><StatusBadge status={revision.status}/></td><td>{formatDate(revision.updated_at||article?.updated_at)}</td><td>{article?.status==="published"?<Link href={`/article/${article.slug}`}>open</Link>:"not published"}</td><td className="table-actions"><Link href={`/dashboard/articles/${id}/edit`}>{revision.status==="pending_review"?"View":"Edit / propose"}</Link><Link href={`/dashboard/articles/${id}/history`}>History</Link></td></tr>})}</tbody></table>}</>}
